### PR TITLE
Extract the embedded HTML/CSS out of the code render page

### PR DESCRIPTION
**Pull request by j-f1**
Ref #102. Also kinda fixes #142.

### CODE REVIEW

**Comment by ry** [comment]
I've deployed this to the site, but it looks odd:

Screen Shot 2019-08-21 at 9 29 53 PM

**Comment by j-f1** [comment]
It looks like the CSS and JS files are failing to load. Here’s the error:

> The Lambda function returned invalid json: The json output must be an object type. 

And here’s the request ID: `_cLtEP0YDGfZUQ7p6jpb6h-MOGBasNl_0upARFX9uTMsHzjXJ2s4VA==`

Is there any way for you to check the logs or something to see what went wrong? It works fine for me locally.

**Comment by ry** [comment]
@j-f1 Is this still relevant? Please close or rebase.

**Comment by j-f1** [comment]
Rebased 👍

**Comment by j-f1** [comment]
No worries!

**Pull request merged**
