### PR TITLE
Revert code (attempting to fix 500 errors without actually digging in)

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by j-f1** [comment]
Do you have any stack traces for the errors?

**Comment by ry** [comment]
@j-f1 The only errors i see in the logs look like this:
```
(ZpRV7YcubnNZW_FNy0cWuHroMlj2l3fNoT9wvsByFmvGiP8EKgHURA==) ERROR Validation error: The Lambda function returned an invalid json output, parsed json should be an object type.
```
... TBH I don't know how to drill down in CloudWatch to find errors.

**Comment by ry** [comment]
@j-f1 My suspicion is that it's timing out. Is there a way to easily turn off the TypeScript parsing?

**Comment by ry** [comment]
I have deployed this revert, and things seem to be running better now...

**Comment by j-f1** [comment]
Change this:

https://github.com/denoland/registry/blob/a59b596a876598c3c7d7fd5cb6b4c3e11a6f06b6/src/render_code.js#L9-L27

to this:

```js
function getLines(pathname, code, opts) {
  return {
    err: null,
    lines: code.split("\n").map(escapeHtml)
  };
}
```

**Comment by ry** [comment]
@j-f1 Thanks - I've made that change and it works. In the coming weeks I'm going to start working on the website more - for now this bandaid will work.

**Pull request merged**
