### PR TITLE
Add deno_init to database.json

### PR DESCRIPTION
**Pull request by maxuuell**
Add new script to set up a basic deno repo.  Meant to be installed with `deno_isntaller`.  Will add to the script as things progress.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@maxuuell cool! Just a heads up, there are already two other repos with same name:
https://github.com/zhmushan/deno_init
https://github.com/syumai/deno-libs/tree/master/denoinit

CC @zhmushan @syumai maybe we could compile everything into one solid starter project?

**Comment by maxuuell** [comment]
I did see that there were other init projects. I just didn't see them here in the registry. I thought this would just be a good project to build on over time.

**Comment by bartlomieju** [comment]
> I did see that there were other init projects. I just didn't see them here in the registry. I thought this would just be a good project to build on over time.

Definitely is! If I may suggest - having ability to use different repos as templates would be awesome 😄 
eg.:
```
deno_init my_awesome_project https://github.com/foo/deno_minimal
```

**Comment by maxuuell** [comment]
I was actually thinking of allowing a user to pass in a command line prompt to tell the script to set up a certain repo.

`deno_init my_server --app-server` --> would set up a server template with oak

etc...

Thoughts?

**Comment by hayd** [comment]
adding travis/appveyor/azure would also be nice. 😬

**Pull request merged**
